### ISSUE TITLE
Add NSP security check

### ISSUE THREAD

**Issue by diracdeltas** [brave/vault#45]
Can basically copy/paste https://github.com/brave/browser-laptop/pull/205

**Comment by therealklanni** [comment]
I'll take a look at these others (later) if no one else beats me to it. I wasn't sure which other projects might benefit from it. :+1:

**Comment by mrose17** [comment]
@therealklanni - can you do me a favor and take a look at https://github.com/brave/vault/tree/issue-41 ... i tracked down all the dependencies and did the minimal amount of work to get the intermediate packages to work. this branch is not suitable for master, but at least it shows us what needs to get updated... thanks!

**Comment by therealklanni** [comment]
Did you mean https://github.com/brave/vault/tree/issue-45?

**Comment by mrose17** [comment]
sorry, right you are! many thanks!

**Comment by therealklanni** [comment]
Sorry I haven't gotten around to looking yet. What exactly did you want me to check into on that?

**Comment by mrose17** [comment]
no worries! just wanted to see if you think i got them all...

**Comment by therealklanni** [comment]
Ah, OK. I'll take a look when I get a chance (tonight if not sooner).

**Comment by therealklanni** [comment]
So I looked at the packages. I think any of the ones that were on the latest version of request can go back to using the official request package, because that version of hawk should install. As far as the others, looks good.

**Comment by mrose17** [comment]
great! any changes we can make now to either brave/vault or brave/vault-client ?

**Comment by therealklanni** [comment]
Looks like BitGo just removed the chain-node dependency as well, so we might be able to use their latest release

https://github.com/BitGo/BitGoJS/issues/20#issuecomment-175343660

**Comment by mrose17** [comment]
great, let me try that out.

**Comment by mrose17** [comment]
@therealklanni - just checking in. any motion from anyone? thanks!

**Comment by therealklanni** [comment]
Hey, I've been busy, sorry I haven't followed up. I believe the issue was resolved by bitgo@0.11.65.

**Comment by mrose17** [comment]
brilliant! i plan to do a commit to the integration branch on monday with the test enabled...

many thanks!

**Comment by mrose17** [comment]
fixed in https://github.com/brave/vault/commit/09efc74f2eab7300aba509dd1dbd7df702688e8a

**Comment by mrose17** [comment]
@therealklanni - thanks for driving this. i believe the current branches for vault and vault-client now pass!
