### ISSUE TITLE
Travis build status is private

### ISSUE THREAD

**Issue by salty-horse** [brave/vault#47]
The README links to the Travis page https://travis-ci.com/brave/vault which requires authentication.

Since the project is open-source, shouldn't the Travis page also be open?

**Comment by bbondy** [comment]
Yep that needs to be fixed now, thanks for posting!

**Comment by mrose17** [comment]
@bbondy - thanks. since you took the token on this, please let me audit the PR!

**Comment by mrose17** [comment]
i'll take care of it... (since travis-ci.org is a bit cranky these days...)

**Comment by bbondy** [comment]
thanks

**Comment by mrose17** [comment]
resolved. i truly wish that we could host open source projects in travis-ci.com ... very annoying to have to recreate it all...
